languageName = "日本語"
weight = 1

[params]
  displayName = "日本語"
  isoCode = "ja"

[params.author]
  name = "GesonAnko"
  email = "shimomura.yasuhiro@gop.co.jp"
  image = "images/thumbnail.png"
  headline = "自律機械知能に脳みそを焼かれた人。"
  links = [
    { github = "https://github.com/Geson-anko" },
    { twitter = "https://x.com/GesonAnkoVR" },
    { discord = "https://discord.gg/bDW3Xhj6f7" },
  ]
