[[main]]
  name = "ホーム"
  pageRef = "/"
  weight = 10

[[main]]
  name = "プロフィール"
  pageRef = "about"
  weight = 20

[[main]]
  name = "ブログ"
  pageRef = "blog"
  weight = 30

[[main]]
  name = "プロジェクト"
  pageRef = "projects"
  weight = 40
