favicon = "images/icon.png"
defaultOgImage = "images/thumbnail.png"
colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true

[homepage]
  layout = "background"
  homepageImage = "images/thumbnail.png"
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/blog"
  cardView = true

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = true
  showBreadcrumbs = true
  showTableOfContents = true
  showWordCount = true
  showEdit = false
  showComments = false

[list]
  showBreadcrumbs = true
  showTableOfContents = false
  groupByYear = true
  cardView = true

[taxonomy]
  showTermCount = true

[fathomAnalytics]
  # placeholder

[verification]
  google = "google2a5f02b4a1a1dece"

[params.katex]
  enable = true
